apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: nginx-propagation
  namespace: default
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: nginx-app
  placement:
    clusterAffinity:
      clusterNames:
        - local-cluster # 这里完美匹配两台机器上各自加入的 local-cluster