apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: demo-nginx-pp
  namespace: {{ .Release.Namespace }}
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: {{ include "my-helm-app.fullname" . }}
    - apiVersion: v1
      kind: Service
      name: {{ include "my-helm-app.fullname" . }}
  placement:
    clusterAffinity:
      clusterNames:
        - pj-cluster
        - zp-cluster